### ISSUE TITLE
How to set isProduction, userId, and password in AbstractRequest?

### ISSUE THREAD

**Issue by kurniajigunawan** [David-Kurniawan/omnipay-faspay#1]
Hello, I have a check on class `AbstractRequest`, but I'm a little bit confusing to set my `userid `and `password`. I'm no idea to set `userid`, `password` and change variable `isProduction `to `true`. Should I do hard code on `AbstractRequest`?

**Comment by 69dev69dev** [comment]
hi @kurniajigunawan 

Thank you, i've been update the codes for more flexible
[#1.0.1](https://github.com/David-Kurniawan/omnipay-faspay/releases/tag/1.0.1)

u can have a look the example [here](https://github.com/David-Kurniawan/omnipay-faspay/blob/master/tests/GatewayTest.php)
